config/routes.rb
Rails.application.routes.draw do

  namespace :managers do
	  get    "/login"   => "sessions#new"
	  post   "/login"   => "sessions#create"
	  delete "/logout"  => "sessions#destroy"
	end

  resources :tickets do
    resources :replies
  end

  root 'tickets#new'
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :ticket
  has_many :replies, as: :repliable, dependent: :destroy

  after_save :send_mailer

  def send_mailer
    TicketMailer.replied(self.ticket).deliver_now
  end
end

app/models/ticket.rb
require 'elasticsearch/model'

class Ticket < ActiveRecord::Base
  include Elasticsearch::Model

  validates :from_name, :from_email, :subject, :body, presence: true
  has_many :replies, :dependent => :destroy

  def as_indexed_json(options={})
    as_json(
      only: [:id, :subject, :from_name, :from_email, :body, :uniq_identifier]
    )
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
    :message => "InvalidEmail" }, presence: true, uniqueness: { message: "EmailAlreadyInUse" }, :if => :email_changed?
  validates :password, :format => { :with => /(?=.*[a-z])(?=.*[A-Z])(?=.*\W)(?=.{8,})/,
    :message => "InvalidPassword"}, presence: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Managers::SessionsHelper

  helper_method :current_user

  protect_from_forgery with: :exception

  def current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in_manager
    redirect_to new_ticket_path unless logged_in?
  end
end

app/controllers/managers/sessions_controller.rb
class Managers::SessionsController < ApplicationController
  before_action :logged_in_manager, only: [:destroy]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to tickets_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to managers_login_path
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def create
    @ticket = get_ticket
    @reply = @ticket.replies.create(reply_params)
    if @reply.save
      @reply.update_attribute(:from, current_user.email)
      flash[:success] = "Reply was saved!"
    else
      flash.now[:danger] = "error"
    end
    redirect_to ticket_path(@ticket)
  end

  private

  def get_ticket
    @ticket = Ticket.find_by_id(params[:ticket_id]) if params[:ticket_id]
  end

  def reply_params
    params.require(:reply).permit(:text)
  end
end

app/controllers/tickets_controller.rb
require 'rake'  
load File.join(Rails.root, 'lib', 'tasks', 'elasticsearch.rake')

class TicketsController < ApplicationController
  before_action :logged_in_manager, only: [:index]

  def index
    if params[:search].blank?
      @tickets = Ticket.all.order('created_at desc')
    else
      search
    end
  end

  def show
    @ticket = get_ticket
    @reply = @ticket.replies.build
    @replies = @ticket.replies.order('created_at desc')
  end

  def new
    current_user ? (redirect_to tickets_path) : @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      assing_uniq_identifier(@ticket)
      Rake::Task['elasticsearch:sync_elasticsearch'].invoke
      TicketMailer.ticket_created(@ticket).deliver_now
      flash[:notice] = "Ticket was saved"
    else
      flash[:error] = @ticket.errors.full_messages.to_sentence
    end
    redirect_to new_ticket_path
  end

  def edit
    @ticket = get_ticket
  end

  def update
    @ticket = get_ticket
    if @ticket.update_attributes(ticket_params)
      TicketMailer.ticket_created(@ticket).deliver_now
      flash[:notice] = "Ticket was updated"
      redirect_to ticket_path(@ticket)
    else
      flash[:error] = @ticket.errors.full_messages.to_sentence
      redirect_to edit_ticket_path(@ticket)
    end
  end

  private

  def search
    @tickets = Ticket.search(params[:search]).results
    if @tickets.count == 1
      ticket = @tickets.first
      redirect_to ticket_path(ticket["_id"])
    end
  end

  def ticket_params
    params.require(:ticket).permit(:subject, :body, :uniq_identifier, :from_name, :from_email)
  end

  def get_ticket
    @ticket = Ticket.find(params[:id])
  end

  def assing_uniq_identifier(ticket)
    ticket.update_attribute(:uniq_identifier, random_id)
  end

  def random_id
    random_string + "-" + random_int_string + "-" + random_string + "-" + random_int_string
  end

  def random_string
    3.times.map { [*'a'..'z'].sample }.join.upcase
  end

  def random_int_string
    3.times.map { [*'0'..'9'].sample }.join
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/managers/sessions_helper.rb
module Managers::SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketsProj</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if logged_in? %>
      <ul>
        <li><%= link_to "Log out", managers_logout_path, method: :delete %></li>
      </ul>
    <% else %>
      <ul>
        <li><%= link_to "Log in", managers_login_path %></li>
      </ul>
    <% end %>
    <div>
      <% flash.each do |key, value| %>
        <div><%= value %></div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/replies/_reply.html.erb
<li>
  (<%=reply.created_at %>)
  <p><strong>Reply: </strong>
    <p>From: <%= reply.from %></p>
    <p>Body: <%= reply.text %></p>
  </p>
</li>

app/views/tickets/_form.html.erb
<%= form_for [@ticket] do |f| %>
  <p><%= f.label :from_name %>
  <%= f.text_field :from_name %></p>

  <p><%= f.label :from_email %>
  <%= f.email_field :from_email %></p>

  <p><%= f.label :subject %>
  <%= f.text_field :subject %></p>

  <p><%= f.label :body %>
  <%= f.text_area :body %></p>

  <%= f.submit "Submit the ticket" %>
<% end %>

app/views/tickets/edit.html.erb
<%= render partial: "form" %>

app/views/tickets/index.html.erb
<%= form_for tickets_path, method: :get do |f| %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Go", name: nil %>
    </p>
  <% end %>
<ul>
  <% @tickets.each do |ticket| %>
    <li>
      <p>ID: <%= ticket.uniq_identifier %></p>
      <p>From(name): <%= ticket.from_name %></p>
      <p>From(email): <%= ticket.from_email %></p>
      <p>Subject: <%= ticket.subject %></p>
      <p>Body: <%= ticket.body %></p>
      <p><%= link_to "show", ticket_path(ticket)%></p>
    </li>
  <% end %>
</ul>

app/views/tickets/new.html.erb
<%= render partial: "form" %>

app/views/tickets/show.html.erb
<p>ID: <%= @ticket.uniq_identifier %></p>
<p>From(name): <%= @ticket.from_name %></p>
<p>From(email): <%= @ticket.from_email %></p>
<p>Subject: <%= @ticket.subject %></p>
<p>Body: <%= @ticket.body %></p>
<p>Created: <%= @ticket.created_at %></p>
<p>Updated: <%= @ticket.updated_at %></p>

<h2>Reply:</h2>
<% if current_user %>
  <%= form_for [@ticket, @reply] do |f| %>
    <p>
      <%= f.text_area :text, placeholder: 'Enter your reply'%>
    </p>
    <p>
      <%= f.submit "Save reply"%>
    </p>
  <% end %>
<% end %>

<% unless @ticket.replies.empty? %>
  <ul>
    <%= render :partial => 'replies/reply', :collection => @replies %>
  </ul>
<% end %>